version: '3'

services:
  db:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobileapp
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      